{
  try {
    testForAll(domain,rule);
  }
 catch (  AssertionError e) {
    assumeNoException(e);
  }
}
